### ISSUE TITLE
[Fix] 자체 QA 진행

### ISSUE THREAD

**Issue by mcrkgus** [Team-Hankki/hankki-iOS#143]
## 🛠 Issue

- 자체 QA 진행합니다. 

## 📝 To-do

- [x] 홈화면 바텀시트 위로 스와이프 시, 필터링 겹치는 현상 -> 필터링 hidden 처리 
- [x] 지도 핀 선택 후 대학 변경 시 info card view 및 지도 핀 초기화 
- [ ] 메뉴 제보 이후 홈화면 업데이트 안 됨 
- [ ] naver 로고 우측 상단으로 이동
