### ISSUE TITLE
[Fix] 2차 자체 QA 진행

### ISSUE THREAD

**Issue by EunsuSeo01** [Team-Hankki/hankki-iOS#161]
## 🛠 Issue
- 2차 자체 QA를 진행합니다.
- 디자인, 기획 각종 수정사항을 반영합니다.

## 📝 To-do

- [x] 제보 완료 후 랜덤 감사 메세지 2줄짜리 안 잘리게 수정
- [x] 제보 완료 화면 그라디언트 재조정 (위에 왜인지 잘림) -> 네비바 배경색 clear로 설정하여 해결
- [x] 식당 상세 보기 화면 제보하기 버튼 밑에 배경색 재조정
- [x] 식당 상세 보기 -> 홈 화면 스와이프로 뒤로 가기 구현
- [x] 검색 화면 컬뷰 셀 label 폰트 왜 이래...? 수정
- [x] 검색 화면 컬뷰 셀 주소 label이 체크 버튼 뒤까지 넘어가는 이슈 수정
- [x] 식당 상세 보기 잘못된 정보 제보 시 알림창 돌아가기 버튼 기능 수정
- [x] 검색 결과 EmptyView 적용 및 검색어만 다른 색 적용
- [x] 식당 제보 완료 화면에서 스와이프로 뒤로 못 가게 막기
