### ISSUE TITLE
[Fix] 3차 자체 QA 진행

### ISSUE THREAD

**Issue by EunsuSeo01** [Team-Hankki/hankki-iOS#164]
## 🛠 Issue

- 3차 자체 QA를 진행합니다.
- 디자인, 서버의 수정사항을 반영합니다.
## 📝 To-do

- [x] 제보하기 버튼 활성화 로직 수정 -> 아무래도 Rx 써야될 듯 이거 -> Rx 없이 해결하다. 레전드.
- [x] 식당 상세 보기 info 컬뷰 그림자 수정
- [x] 내 족보 추가 이후 토스트 띄우는 부분 코드 수정
- [x] 검색창 x 버튼 클릭 시 검색 결과 목록 초기화
- [x] 검색창 x 버튼 클릭 시 이전에 엠티뷰 떠있었다면 엠티뷰 제거
- [x] 재검색 시 검색 결과 목록 초기화
- [x] 식당 상세 보기 메뉴 이름이랑 가격 사이 dot (시간 나면) -> 안 났는데 어쩌다 보니 함 ㅋㅋ
- [x] 식당 이름 10글자 이후부터 truncated 되도록 구현
- [x] 식당 상세 보기 메뉴 글자수에 따른 dot line 레이아웃 동적 변경 구현
- [x] 식당 상세 보기 메뉴 가격 천단위 포맷팅
- [x] 이미 등록된 식당인지 판별하는 API 추가된 예외 처리
- [x] 다른 학교에 이미 제보된 식당을 우리 학교에 제보하는 API 연동
- [x] 식당 검색 쪽 새로 추가된 Alert ‘이동하기’, ‘추가하기’ 화면 이동 구현
- [x] 제보하기 메인 검색창 최대 글자 설정, 동적 width 설정
