### ISSUE TITLE
[Fix] 자체 QA 2차

### ISSUE THREAD

**Issue by mcrkgus** [Team-Hankki/hankki-iOS#167]
## 🛠 Issue

- 2차 QA를 자체적으로 진행 
- 디자인 변경사항 반영

## 📝 To-do

- [x]  naver 로고 우측 상단으로 이동
- [x] Home NavigationBar Font 변경
- [x] TabBar 변경
- [x] 족보 없을 시 emptyView
- [x] (이후 위치정보 미동의시) 우선 둘러볼게요 클릭 후 진입시 서울시립대 포커싱
- [x] infoCardView layer 
- [x] chipView Select 시 컬러 변경
