### ISSUE TITLE
[Design] Design 수정사항 반영

### ISSUE THREAD

**Issue by shimseohyun** [Team-Hankki/hankki-iOS#170]
## 🛠 Issue
- 디자인의 수정사항을 반영합니다.

## 📝 To-do

- [x] 로딩 로티 적용
- [x] 모달창 사이즈 변경
- [ ] 색깔이름 변경

- [x] 프로필 단일이미지로 변경
