### ISSUE TITLE
[Fix] 수정사항 반영

### ISSUE THREAD

**Issue by EunsuSeo01** [Team-Hankki/hankki-iOS#171]
## 🛠 Issue

- 남은 디자인 및 서버의 수정사항을 반영합니다.
- 이외의 남은 작업도 같이 마무리합니다.

## 📝 To-do

- [x] 식당상세 응답 null 줄 때 디폴트 이미지
- [x] 제보하기 뷰 업데이트된 간격으로 수정
- [x] Alert 닉네임 값 연결
- [ ] Alert 닉네임 글자만 색 다르게
- [x] 식당 삭제 API 연동
- [x] 제보 완료 화면 식당 이름 최대 글자 넘으면 크롭 및 뷰 레이아웃 수정
- [x] 제보하기 메뉴 가격 에러 테두리 유지
