### ISSUE TITLE
[Fix] 자체 QA 3차

### ISSUE THREAD

**Issue by mcrkgus** [Team-Hankki/hankki-iOS#176]
## 🛠 Issue

- Design 변경 사항 반영
- 버그 픽스 

## 📝 To-do

- [x] (이후 위치정보 동의시) 찾는 대학교가 없어요 우선 둘러볼게요 클릭 후 진입시 홈에서 대학교 선택란이 ‘전체’로 뜨면서 내위치가 포커싱
- [x] BottomSheet, chip Animation duration 수정 
- [x] HomeView Navigation 대학 좌측 이동
- [x] markCardInfoView Category Tag 변경
