### ISSUE TITLE
[Fix] 1차 디자인 QA

### ISSUE THREAD

**Issue by mcrkgus** [Team-Hankki/hankki-iOS#181]
## 🛠 Issue

- 디자인 관련 수정사항 및 QA 반영

## 📝 To-do

- [x] 과녁 아이콘 변경
- [x] BottomSheet Cell title, image Layout 간격 확인
- [x] BottomSheet Cell 중앙정렬
- [x] BottomSheet Cell 사이 간격 조정
- [x] MarkerInfoCardView 
- [x] 필터링 chip title, icon 간격 변경
- [x] 필터링 chip normal, select color 분기처리
- [x] 식당 리스트 없을 경우 emptyView 이미지랑 라벨 간격 넓히기
- [x] TabBar Line
