### ISSUE TITLE
[Fix] 진짜 QA 1차

### ISSUE THREAD

**Issue by EunsuSeo01** [Team-Hankki/hankki-iOS#187]
## 🛠 Issue

- 1차 전체 QA 후 발견된 이슈 사항들을 해결합니다.

## 📝 To-do

- [x] 좋아요 추가 시 뷰 반영 바로 안 됨 -> handleNetworkResult로 바꾸면서 completion 호출 부분을 삭제해버림; 다시 추가해서 해결
- [x] 식당 검색 결과에서 선택 해제 시 하단 버튼 비활성화 안 되는 이슈 해결
- [x] 식당 검색 결과에서 특정 식당을 선택하고 **하단 버튼을 눌렀을 때에만!!** 제보 메인 검색창에 식당 이름이 채워지게 수정
- [x] 제보 사진 첨부 시 간격 수정
