### ISSUE TITLE
[Fix] 1차 기능 QA

### ISSUE THREAD

**Issue by mcrkgus** [Team-Hankki/hankki-iOS#193]
## 🛠 Issue

- 기능 관련 QA 반영

## 📝 To-do

- [x] Filtering Chip BottomSheet 올라왔을때 hidden
- [ ] TotalListBottomSheet 올려놓은 후에 다른 버튼(제보하기/마이페이지)을 누르고 다시 홈으로 빠질 시에 BottomSheet 내려가지 않고 올라오기
- [x] TotalListBottomSheet Handler 영역 넗히기
- [x] 세 개의 필터가 화면에서 겹치지 않고 하나씩 작동하는가
- [x] 바텀시트를 아래로 내렸을 때 식당 정보들이 위로 올라오면서 내려가는가
- [x] 위치 정보 미동의 시 -> 대학교 더 둘러볼게요 클릭 -> 시립대학교 포커싱
- [ ] 위치 정보 동의 시 -> 대학교 더 둘러볼게요 클릭 -> 현재 나의 위치 포커싱 
- [x] 위의 사항에서 NaviBar "전체"로 변경 후 식당 모든 리스트 api 연결
