### ISSUE TITLE
[Fix] 1.5차 디자인 QA

### ISSUE THREAD

**Issue by mcrkgus** [Team-Hankki/hankki-iOS#198]
## 🛠 Issue

- 1.5차 디자인 QA

## 📝 To-do

`제보하기`
- [x] NavigationBar Back Button Layout 바깥쪽으로(10)
- [x] 대표 음식 이미지 첨부하기(선택) 테두리 점선으로
- [x] 메뉴 등록 가격 TextField Select 되었을 때 테두리 (두께 1.5, 컬러 gray600)으로 변경
- [x] 메뉴 등록 가격 TextField trailing Layout 마진 다시
- [x] 메뉴 추가하기+ 버튼] + 아이콘 변경, leading 마진 22로 통일
- [x] n번째 제보예여 -> 식당이 선택되면 gray600 / default는 red500
- [x] 식당 선택 시 dropDown 화살표 아이콘 변경 (~을 제보할래요 옆에)
- [x] 이미지 선택 시 x 버튼 alpha값 제거해주세용
- [x] 메뉴 가격 초과 시 8000원 이하만 가능해요 -> 8천원 이하만 가능해요 워딩 변경

`제보완료` 
- [x] [+나의 족보에 추가] Font 변경, Color 확인
- [x] 등록된 식장 정보 View? BackgroundColor white
- [x] 족보 추가 후 toastMessage -> 이동 을 “보기”로 워딩 변경
- [ ] toastMessage 표출 후 이미지 이상해짐… (은수QA2, 3번 사진)
