### ISSUE TITLE
[Fix] 1.5차 기능 QA

### ISSUE THREAD

**Issue by mcrkgus** [Team-Hankki/hankki-iOS#210]
## 🛠 Issue

- 1.5차 기능 QA 

## 📝 To-do

- [x] 상단 카테고리 필터 Button - 가격대, 정렬 2번 클릭 시 hidden 
- [x] 상단 카테고리 필터 Button 터치 영역 넓히기 
- [x] 대학교 선택 후 좌표 포커싱 Console 확인 
- [x] TotalListBottomSheet 스크롤 영역
- [x] 찾는 대학교가 없어요! 둘러볼게요 에서 전체가 아니라 한끼 대학교 워딩 변경
- [x] Target Button 사라짐 이슈 
- [x] MarkerCardInfoView Layout 조정
