### ISSUE TITLE
[Fix] DTO 수정 및 대학 위치 설정 

### ISSUE THREAD

**Issue by mcrkgus** [Team-Hankki/hankki-iOS#212]
## 🛠 Issue

- DTO 수정 
- 대학 위치 오류 

## 📝 To-do

- [x] 대학 선택 시 필터링 초기화 
- [x] 음식 종류 필터링 - 그래픽 이미지는 48px, 그래픽과 글자 사이의 여백이 기존 8px -> 6px 로 변경
- [x] 바텀시트 애니메이션 추가 
- [x] emptyView Label 글자 잘림
- [x] 온보딩 디자인 이슈
