### ISSUE TITLE
[Fix] 1.5차 기능 QA

### ISSUE THREAD

**Issue by EunsuSeo01** [Team-Hankki/hankki-iOS#213]
## 🛠 Issue

- **[2차 QA D-DAY]** 1.5차 기능 QA를 진행합니다.

## 📝 To-do

- [x] 전체 → 식당 세부 정보 → 홈화면 진입 시 이전에 선택한 대학교가 뜨는 이슈 해결
- [x] 네비바 오류 (제보하기 갔다가 홈화면 나오면 제보하기로 뜸) 해결
- [x] '전체'일 때 대학교를 먼저 선택하라는 팝업 띄우기
- [x] 홈 VC locationServicesEnabled 보라색 경고 해결
- [x] '전체'일 때 리스트 바로 안 불러와지는 이슈 해결
