### ISSUE TITLE
[Feat] 메인 홈화면 구현

### ISSUE THREAD

**Issue by mcrkgus** [Team-Hankki/hankki-iOS#22]
## 🛠 Issue

- 바텀시트가 없는 메인 홈화면을 구현합니다. 

## 📝 To-do

- [x] 네비게이션바 (대학 선택 화면으로 이동)
- [x] CocoaPod 설치 (드롭다운)
- [x] 네이버 클라우드 지도 API 설정
- [x] 지도 마커, 배경 선택 제스처 인식
- [x] 필터링 버튼 (종류, 가격, 정렬) 분기처리
