### ISSUE TITLE
[Fix] 2차 QA 반영

### ISSUE THREAD

**Issue by mcrkgus** [Team-Hankki/hankki-iOS#223]
## 🛠 Issue

- 2차 QA 반영

## 📝 To-do

- [x] 지도 위치 포커싱 조정(경도 20올리기)
- [x] 홈화면 지도 pin 전체 실시간 업데이트 
- [x] 홈화면 지도 줌인 default 값 정해놓기
