### ISSUE TITLE
[Fix] 2차 QA 반영

### ISSUE THREAD

**Issue by EunsuSeo01** [Team-Hankki/hankki-iOS#224]
## 🛠 Issue

- 2차 QA 반영
## 📝 To-do

- [x] 검색창에서 무언가를 검색해서 뜨는 화면이 바뀌면 버튼 비활성화함
- [x] 이미지 압축 관련 모달창 추가
- [x] 디자인 QA 반영
