### ISSUE TITLE
[Fix] 디자인 실시간 QA 및 이미지 이슈 해결

### ISSUE THREAD

**Issue by EunsuSeo01** [Team-Hankki/hankki-iOS#242]
## 🛠 Issue

- 디자인 실시간 QA
- 이미지 이슈 해결

## 📝 To-do

- [x] 제보하기 상단 오프셋 제거
- [x] 식당 선택 시 제보수 label 색 변경
- [x] 다른 족보에도 추가 뜨게 주석 해제
- [x] 제보 완료 화면 gradient 최초 1번만 적용되게 수정
- [x] 제보하기 메뉴 간격 수정
- [x] 이미지 로직 수정
