### ISSUE TITLE
[Feat] 2차 스프린트 Home 수정

### ISSUE THREAD

**Issue by mcrkgus** [Team-Hankki/hankki-iOS#256]
## 🛠 Issue

- 2차 스프린트 진행
- Home 화면 변경 

## 📝 To-do

- [x] Navigation Bar Icon, Font 
- [x] Filtering Chips Icon, Font
- [x] Filtering Chips status (default, press, selected)
- [x] Map pin image
