### ISSUE TITLE
[Design] Mypage, Create Zip QA 사항 반영

### ISSUE THREAD

**Issue by shimseohyun** [Team-Hankki/hankki-iOS#268]
## 🛠 Issue
- 10월 8일 QA 이후 발생한 수정사항을 수정합니다
- 함윤정양에게 이 이슈를 바칩니다

## 📝 To-do
- [x] 상단 탭 ‘마이'없애기
- [x]  마이페이지 프로필 이미지 교체
- [x]  새로운 식당 족보 뒤로가기와 타이틀 사이 간격 조정
- [x] 한끼리스트카드 하트버튼빼고 이전디자인으로 돌리기
