### ISSUE TITLE
[Fix] 2차 스프린트 디자인 QA 반영

### ISSUE THREAD

**Issue by EunsuSeo01** [Team-Hankki/hankki-iOS#273]
## 🛠 Issue

- 2차 스프린트 디자인 QA를 반영합니다.

## 📝 To-do

- [x] 메뉴 추가/수정하기 터치 영역 넓히기
- [x] 폰트 subtitle3로, 세로도 가로 동적 값 - 5로
- [x] 상세 화면에 메뉴 데이터 바로 업데이트 되도록
- [x] cornerRadius 변경
- [x] 메뉴이름, 메뉴가격 띄어쓰기
- [x] 디자인 모드로 바꿔서 폰트 재확인
- [x] 적용 버튼 -> 수정 완료 버튼으로 변경
