### ISSUE TITLE
[Feat] 둘러보기 기능 추가 

### ISSUE THREAD

**Issue by mcrkgus** [Team-Hankki/hankki-iOS#274]
## 🛠 Issue

- 둘러보기 기능 마무리 

## 📝 To-do

- [x] HomeViewModel 에러 핸들링
- [x] 둘러보기 클릭 시, 홈으로 바로 이동
- [x] 모든 액션 막힘 (리스트만 볼 수 있게, 정렬까지) 
- [x] 불필요한 액션 시, 얼럿창 노출
