### ISSUE TITLE
[Fix] 2차 스프린트 디자인 QA 

### ISSUE THREAD

**Issue by mcrkgus** [Team-Hankki/hankki-iOS#278]
## 🛠 Issue

- 2차 스프린트 디자인 QA 진행

## 📝 To-do

- [x] 홈 네비바 학교 아이콘 좀 아래로
- [x] 홈 네비바 leading 값 필터칩이랑 똑같게 
- [x] 홈 필터칩 텍스트 변경
- [x] 홈 필터칩 그림자 
- [x] 홈 필터칩 셀렉 - 취소 후 text color 연함
- [x] 타겟버튼 살짝 오른쪽으로 이동
- [x] 탭바 아이콘, 텍스트 간격 0으로
