### ISSUE TITLE
[Feat] Univ Select View

### ISSUE THREAD

**Issue by shimseohyun** [Team-Hankki/hankki-iOS#28]
## 🛠 Issue
- 대학 선택 뷰를 만듭니다

## 📝 To-do

- [x] header 부분 만들기
- [x] collection View (univ)
- [x] 선택 버튼 만들기
