### ISSUE TITLE
[Feat] 제보하기 식당 검색, 이미지 첨부 뷰 및 식당 종류 셀 스타일 구현

### ISSUE THREAD

**Issue by EunsuSeo01** [Team-Hankki/hankki-iOS#46]
## 🛠 Issue
- 제보하기 뷰의 식당 검색 뷰를 구현합니다.
- 제보하기 뷰의 갤러리에서 이미지 선택하는 기능을 구현합니다.

## 📝 To-do
- [x] 식당 검색 뷰 구현
- [x] 식당 종류 뷰 선택 및 선택 해제 기능 구현
- [x] 갤러리에서 이미지 선택 기능 구현
