### ISSUE TITLE
[Feat] 필터링 Detail 

### ISSUE THREAD

**Issue by mcrkgus** [Team-Hankki/hankki-iOS#47]
## 🛠 Issue

- 필터링 chip button에 대해 세부 작업을 합니다. 

## 📝 To-do

- [ ] `종류` 필터링 UICollectionView
- [ ] `가격대` 필터링 DropDown
- [ ] `정렬` 필터링 DropDown
- [ ] DropDown 설치 
- [ ] 필터링 메뉴 선택 후 chip 디자인 변경
