### ISSUE TITLE
[Feat] 식당 등록 완료 UI 구현

### ISSUE THREAD

**Issue by EunsuSeo01** [Team-Hankki/hankki-iOS#58]
## 🛠 Issue
- 식당 등록 완료 화면(제보하기(3) 화면)을 구현합니다.

## 📝 To-do
- [x] 화면 UI 구현
- [x] 내 족보에 추가 버튼 클릭 시 나의 식당 족보 바텀 시트와 연결
- [x] 홈으로 버튼 액션 구현
- [x] 내 족보에 한번 추가한 이후에는 **다른 족보에도 추가**로 텍스트 변경 구현
