### ISSUE TITLE
[Feat] 식당 상세 정보 

### ISSUE THREAD

**Issue by EunsuSeo01** [Team-Hankki/hankki-iOS#67]
## 🛠 Issue
- 식당 카드 클릭 시 뜨는 식당 세부 정보 화면을 구현합니다.

## 📝 To-do
- [ ] 식당 세부 정보 기본 UI 구현
- [ ] 메뉴 편집 버튼 클릭 시 준비 중 Alert 띄우기
- [ ] 나의 족보 리스트 바텀시트와 연결
- [ ] 플러스 버튼 클릭 시 나의 족보에 추가되었습니다 토스트뷰 띄우기
- [ ] 제보하기 클릭 시 Alert 띄우기
