### ISSUE TITLE
[Docs] README 수정

### ISSUE THREAD

**Issue by shimseohyun** [Team-Hankki/hankki-iOS#70]
## 🛠 Issue
- 리드미를 수정합니다.

## 📝 To-do
- [x] 프로필 사진 변경
- [x] 맡은 일 수정
- [x] 사용 라이브러리 추가
- [ ] 아키텍쳐, 서비스 소개
