### ISSUE TITLE
[Network] 필터링 API 연결 

### ISSUE THREAD

**Issue by mcrkgus** [Team-Hankki/hankki-iOS#75]
## 🛠 Issue

- 필터링과 관련된 API를 연결합니다. 

## 📝 To-do

- [x] 카테고리 필터 드롭다운 정보 조회
- [x] 가격 필터 드롭다운 정보 조회
- [x] 정렬 드롭다운 정보 조회
