### ISSUE TITLE
[Network] 장소 검색 관련 API 연동

### ISSUE THREAD

**Issue by EunsuSeo01** [Team-Hankki/hankki-iOS#89]
## 🛠 Issue
- 식당 장소 검색하기 API를 연동합니다.
- 이미 등록된 식당인지 판별하는 API를 연동합니다.

## 📝 To-do
- [x] 식당 장소 검색하기 API 연동 코드 작성
- [x] 유저가 타이핑 끝나는 시점 감지 후 API 호출
- [x] 데이터 바인딩
- [x] 이미 등록된 식당인지 판별하는 API 연동 코드 작성
